plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - semantic-versioning
#  - name: bleeding-edge/*
#    prerelease: '${name.replace(/^bleeding-edge\//g, "bleeding-edge-")}'