using System.ComponentModel;

namespace S1API.NPCs
{
    /// <summary>
    /// The list of NPCs in the vanilla game.
    /// </summary>
    public enum VanillaNpcList
    {
        [Description("albert_hoover")]
        AlbertHoover,
        [Description("alison_knight")]
        AlisonKnight,
        [Description("anna_chesterfield")]
        AnnaChesterfield,
        [Description("austin_steiner")]
        AustinSteiner,
        [Description("benji_coleman")]
        BenjiColeman,
        [Description("beth_penn")]
        BethPenn,
        [Description("billy_kramer")]
        BillyKramer,
        [Description("brad_crosby")]
        BradCrosby,
        [Description("carl_bundy")]
        CarlBundy,
        [Description("charles_rowland")]
        CharlesRowland,
        [Description("chloe_bowers")]
        ChloeBowers,
        [Description("chris_sullivan")]
        ChrisSullivan,
        [Description("cranky_frank")]
        CrankyFrank,
        [Description("dan_samwell")]
        DanSamwell,
        [Description("dean_webster")]
        DeanWebster,
        [Description("dennis_kennedy")]
        DennisKennedy,
        [Description("donna_martin")]
        DonnaMartin,
        [Description("doris_lubbin")]
        DorisLubbin,
        [Description("elizabeth_homley")]
        ElizabethHomley,
        [Description("eugene_buckley")]
        EugeneBuckley,
        [Description("fiona_hancock")]
        FionaHancock,
        [Description("genghis_barn")]
        GenghisBarn,
        [Description("george_greene")]
        GeorgeGreene,
        [Description("geraldine_poon")]
        GeraldinePoon,
        [Description("greg_fliggle")]
        GregFliggle,
        [Description("hank_stevenson")]
        HankStevenson,
        [Description("harold_colt")]
        HaroldColt,
        [Description("herbert_bleuball")]
        HerbertBleuball,
        [Description("igor_romanovich_door")]
        IgorRomanovichDoor,
        [Description("jack_knight")]
        JackKnight,
        [Description("jackie_stevenson")]
        JackieStevenson,
        [Description("jane_lucero")]
        JaneLucero,
        [Description("javier_perez")]
        JavierPerez,
        [Description("jeff_gilmore")]
        JeffGilmore,
        [Description("jen_heard")]
        JenHeard,
        [Description("jennifer_rivera")]
        JenniferRivera,
        [Description("jeremy_wilkinson")]
        JeremyWilkinson,
        [Description("jerry_montero")]
        JerryMontero,
        [Description("jessi_waters")]
        JessiWaters,
        [Description("joyce_ball")]
        JoyceBall,
        [Description("karen_kennedy")]
        KarenKennedy,
        [Description("kathy_henderson")]
        KathyHenderson,
        [Description("keith_wagner")]
        KeithWagner,
        [Description("kevin_oakley")]
        KevinOakley,
        [Description("kim_delaney")]
        KimDelaney,
        [Description("kyle_cooley")]
        KyleCooley,
        [Description("leo_rivers")]
        LeoRivers,
        [Description("lily_turner")]
        LilyTurner,
        [Description("lisa_gardener")]
        LisaGardener,
        [Description("louis_fourier")]
        LouisFourier,
        [Description("lucy_pennington")]
        LucyPennington,
        [Description("ludwig_meyer")]
        LudwigMeyer,
        [Description("mac_cooper")]
        MacCooper,
        [Description("marco_baron")]
        MarcoBaron,
        [Description("meg_cooley")]
        MegCooley,
        [Description("melissa_wood")]
        MelissaWood,
        [Description("michael_boog")]
        MichaelBoog,
        [Description("mick_lubbin")]
        MickLubbin,
        [Description("molly_presley")]
        MollyPresley,
        [Description("ming")]
        Ming,
        [Description("pearl_moore")]
        PearlMoore,
        [Description("peggy_myers")]
        PeggyMyers,
        [Description("peter_file")]
        PeterFile,
        [Description("philip_wentworth")]
        PhilipWentworth,
        [Description("randy_caulfield")]
        RandyCaulfield,
        [Description("ray_hoffman")]
        RayHoffman,
        [Description("salvador_moreno")]
        SalvadorMoreno,
        [Description("sam_thompson")]
        SamThompson,
        [Description("shirley_watts")]
        ShirleyWatts,
        [Description("stan_carney")]
        StanCarney,
        [Description("tobias_wentworth")]
        TobiasWentworth,
        [Description("trent_sherman")]
        TrentSherman,
        [Description("uncle_nelson")]
        UncleNelson,
        [Description("walter_cussler")]
        WalterCussler,
        [Description("wei_long")]
        WeiLong
    }
}
