name: Verify Successful Build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - bleeding-edge
      - stable

jobs:
  build:
    name: Verify Successful Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
    
      - name: Clone Game Assemblies
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/KaBooMa/ScheduleOneAssemblies.git ./ScheduleOneAssemblies
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
          
      - name: Restore .NET Dependencies
        run: dotnet restore
        
      - name: Copy Game Assemblies into Project
        run: |
          cp -r ./ScheduleOneAssemblies/Il2CppAssemblies ./S1API/Il2CppAssemblies
          cp -r ./ScheduleOneAssemblies/Managed ./S1API/Managed
          
      - name: Run .NET Build for Mono
        run: dotnet build ./S1API/S1API/S1API.csproj -c Mono -f netstandard2.1
        
      - name: Run .NET Build for Il2Cpp
        run: dotnet build ./S1API/S1API/S1API.csproj -c Il2Cpp -f netstandard2.1